services:
  centos:
    container_name: centos7
    image: centos7-python311:latest
    restart: on-failure
    command: ["sleep", "infinity"]
  ubuntu:
    container_name: ubuntu
    image: ubuntu-python311:latest
    restart: on-failure
    command: ["sleep", "infinity"]